const nome = prompt('Digite seu nome completo')
document.body.innerHTML = `O seu nome é: <strong>${nome} </strong><br>`
document.body.innerHTML += `Seu nome tem <strong>${nome.length} letras </strong><br>`
document.body.innerHTML += `A segunda letra do seu nome é: <strong>${nome[1]} </strong><br>`
document.body.innerHTML += `Qual o primeiro indice da letra s no seu nome? <strong>${nome.indexOf('s')} </strong><br>`
document.body.innerHTML += `Qual é o ultimo indice da letra e no seu nome? <strong>${nome.lastIndexOf('e')} </strong><br>`
document.body.innerHTML += `As ultimas tres letras do seu nome são: <strong>${nome.slice(-3)} </strong><br>`
document.body.innerHTML += `As palavras do seu nome são: <strong>${nome.split(' ')} </strong><br>`
document.body.innerHTML += `Seu nome com letras maiusculas é: <strong>${nome.toUpperCase()} </strong><br>`
document.body.innerHTML += `Seu nome com letras minusculas é: <strong>${nome.toLowerCase()}</strong>`